### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by w84v2rhsq4** [loudonclear/cs224final#1]
Hello,
Could you help me, why does rendering differ from yours?

Ubuntu 16
Intel Ivybridge Mobile 
OpenGL core profile version string: 4.2 (Core Profile) Mesa 18.0.5
OpenGL core profile shading language version string: 4.20
OpenGL version string: 3.0 Mesa 18.0.5
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

![Screenshot from 2019-03-12 10-22-53](https://user-images.githubusercontent.com/5450416/54181817-d3cef780-44b0-11e9-97fb-8dcb60cffea3.png)

**Comment by loudonclear** [comment]
You'll want to press the space bar (and wait) to get out of the OpenGL visualizer. Since this is still a cpu implementation, the path traced rendering isn't fast enough for camera manipulation.

**Comment by w84v2rhsq4** [comment]
thank you! it works
